name: TheRedCite
author: Redblaze42
version: 2.0.1
website: redblaze.ovh
main: fr.redblaze.theredcite.main
commands:
  citesetup:
    description: "Configure une cité"
    permission: theredcite.setup
#    usage: "Usage: setworld,spawn,addTrade,createHouse,endHouse"
    aliases:
     - cites
  menu: